FROM grafana/grafana:11.3.0-ubuntu

ENV GF_INSTALL_PLUGINS=yesoreyeram-infinity-datasource,marcusolsson-csv-datasource

ENV GF_PLUGIN_ALLOW_LOCAL_MODE=true

COPY grafana.ini /etc/grafana/grafana.ini

